Update 'bak' script for improved readability
- Modified messages to use bold formatting for file names for better readability.

diff --git a/bin/bak b/bin/bak
--- a/bin/bak
+++ b/bin/bak
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 
-#? bak, Time-stamp: <2024-05-28 Tue 11:27>
+#? bak, Time-stamp: <2024-06-20 Thu 13:42>
 #? Copyright (C) 2020-2024 Fabrice Niessen
 #?
 #? License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
@@ -26,11 +26,15 @@
 # Set -uo pipefail for undefined variable check and pipeline failure propagation.
 set -uo pipefail
 
+# ANSI color codes for bold text.
+bold=$(tput bold)
+normal=$(tput sgr0)
+
 # Define function to check if a file exists and prompt the user to confirm overwrite.
 confirm_overwrite() {
     local file="$1"
     if [[ -e "$file" ]]; then
-        read -p "The file $file already exists. Do you want to overwrite it? (y/N) " confirm
+        read -p "The file ${bold}$file${normal} already exists. Do you want to overwrite it? (y/N) " confirm
         if [[ "$confirm" =~ ^[yY]$ ]]; then
             return 0
         else
@@ -77,7 +81,7 @@ new_file="$(dirname -- "$FILE")/$basename$BAK_EXTENSION$extension"
 
 # Check if the input file exists.
 if [[ ! -f "$FILE" ]]; then
-    printf >&2 "Error: Input file '%s' does not exist.\n" "$FILE"
+    printf >&2 "Error: Input file '${bold}$FILE${normal}' does not exist.\n"
     exit 2
 fi
 
@@ -85,12 +89,12 @@ fi
 if [[ "$rename" == "true" ]]; then
     if confirm_overwrite "$new_file"; then
         mv "$FILE" "$new_file"
-        echo "File renamed from $FILE to $new_file."
+        echo "File renamed from ${bold}$FILE${normal} to ${bold}$new_file${normal}."
     fi
 else
     if confirm_overwrite "$new_file"; then
         cp "$FILE" "$new_file"
-        echo "File copied from $FILE to $new_file."
+        echo "File copied from ${bold}$FILE${normal} to ${bold}$new_file${normal}."
     fi
 fi
 
