Refactor tput usage for consistency in 'bak' and 'unbak' scripts
- Replaced lowercase 'bold' and 'normal' variable names with uppercase 'BOLD'
  and 'RESET' for improved readability and convention adherence.
- Ensured consistent usage of `${BOLD}` and `${RESET}` in printf statements for
  both 'bak' and 'unbak' scripts.

diff --git a/bin/bak b/bin/bak
--- a/bin/bak
+++ b/bin/bak
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 
-#? bak, Time-stamp: <2024-08-13 Tue 11:11>
+#? bak, Time-stamp: <2024-09-19 Thu 15:55>
 #? Copyright (C) 2020-2024 Fabrice Niessen
 #?
 #? License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
@@ -26,15 +26,15 @@
 # Set -uo pipefail for undefined variable check and pipeline failure propagation.
 set -uo pipefail
 
-# ANSI color codes for bold text.
-bold=$(tput bold)
-normal=$(tput sgr0)
+# Define tput formatting variables for reuse.
+BOLD=$(tput bold)
+RESET=$(tput sgr0)
 
 # Define function to check if a file exists and prompt the user to confirm overwrite.
 confirm_overwrite() {
     local file="$1"
     if [[ -e "$file" ]]; then
-        read -p "The file ${bold}$file${normal} already exists. Do you want to overwrite it? (y/N) " confirm
+        read -p "The file ${BOLD}$file${RESET} already exists. Do you want to overwrite it? (y/N) " confirm
         if [[ "$confirm" =~ ^[yY]$ ]]; then
             return 0
         else
@@ -81,7 +81,7 @@ new_file="$(dirname -- "$FILE")/$basename$BAK_EXTENSION$extension"
 
 # Check if the input file exists.
 if [[ ! -f "$FILE" ]]; then
-    printf >&2 "Error: Input file '${bold}$FILE${normal}' does not exist.\n"
+    printf >&2 "Error: Input file '${BOLD}$FILE${RESET}' does not exist.\n"
     exit 2
 fi
 
@@ -89,12 +89,12 @@ fi
 if [[ "$rename" == "true" ]]; then
     if confirm_overwrite "$new_file"; then
         mv "$FILE" "$new_file"
-        printf "File renamed from ${bold}$FILE${normal} to ${bold}$new_file${normal}.\n"
+        printf "File renamed from ${BOLD}$FILE${RESET} to ${BOLD}$new_file${RESET}.\n"
     fi
 else
     if confirm_overwrite "$new_file"; then
         cp "$FILE" "$new_file"
-        printf "File copied from ${bold}$FILE${normal} to ${bold}$new_file${normal}.\n"
+        printf "File copied from ${BOLD}$FILE${RESET} to ${BOLD}$new_file${RESET}.\n"
     fi
 fi
 
diff --git a/bin/unbak b/bin/unbak
--- a/bin/unbak
+++ b/bin/unbak
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 
-#? unbak, Time-stamp: <2024-07-31 Wed 16:09>
+#? unbak, Time-stamp: <2024-09-19 Thu 15:55>
 #? Copyright (C) 2020-2024 Fabrice Niessen
 #?
 #? License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
@@ -54,19 +54,19 @@ file_contains_bak() {
     fi
 }
 
-# ANSI color codes for bold text.
-bold=$(tput bold)
-normal=$(tput sgr0)
+# Define tput formatting variables for reuse.
+BOLD=$(tput bold)
+RESET=$(tput sgr0)
 
 # Check if the backed-up file exists.
 if [[ ! -f "$FILE" ]]; then
-    printf >&2 "Error: Backed-up file '${bold}$FILE${normal}' does not exist.\n"
+    printf >&2 "Error: Backed-up file '${BOLD}$FILE${RESET}' does not exist.\n"
     exit 2
 fi
 
 # Check if the file name contains '_bak'.
 if ! file_contains_bak "$FILE"; then
-    printf >&2 "Error: File '${bold}$FILE${normal}' does not contain '${bold}$BAK_EXTENSION${normal}' in its name.\n"
+    printf >&2 "Error: File '${BOLD}$FILE${RESET}' does not contain '${BOLD}$BAK_EXTENSION${RESET}' in its name.\n"
     exit 2
 fi
 
@@ -90,7 +90,7 @@ original_file_with_extension="$original_file$extension"
 
 # Check if the original file exists.
 if [[ -f "$original_directory/$original_file_with_extension" ]]; then
-    printf "The original file '${bold}$original_file_with_extension${normal}' already exists.\n"
+    printf "The original file '${BOLD}$original_file_with_extension${RESET}' already exists.\n"
 
     # Disable 'set -e' temporarily to handle potential errors during command execution.
     set +e
@@ -114,7 +114,7 @@ fi
 
 # Restore the original file to its original path.
 mv "$FILE" "$original_directory/$original_file_with_extension"
-printf "File restored from ${bold}%s${normal} to ${bold}%s/%s${normal}.\n" \
+printf "File restored from ${BOLD}%s${RESET} to ${BOLD}%s/%s${RESET}.\n" \
        "$FILE" "$original_directory" "$original_file_with_extension"
 
 # Exit with a success code.
