Refactor code

diff --git a/bin/bak b/bin/bak
--- a/bin/bak
+++ b/bin/bak
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 
-#? bak, Time-stamp: <2023-04-06 Thu 11:42>
+#? bak, Time-stamp: <2023-05-12 Fri 11:59>
 #? Copyright (C) 2020-2023 Fabrice Niessen
 #?
 #? License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
@@ -25,49 +25,55 @@
 
 set -e
 
-# Check if a file exists and prompt the user to confirm overwrite.
+# Function to check if a file exists and prompt the user to confirm overwrite.
 function confirm_overwrite() {
     local file="$1"
     if [ -e "$file" ]; then
         printf "The file %s already exists. Do you want to overwrite it? (y/N) " "$file"
         read -r confirm
         if [[ "$confirm" =~ ^[yY]$ ]]; then
-            return 0
+            return 0;
         else
             printf "Operation cancelled.\n"
-            return 1
+            return 1;
         fi
     else
-        return 0
+        return 0;
     fi
 }
 
 # Check if docopts command is available.
-command -v docopts > /dev/null 2>&1 || { printf >&2 'Error: docopts command not found.\n'; exit 2; }
+command -v docopts > /dev/null 2>&1 || {
+    printf >&2 'Error: docopts command not found.\n'
+    exit 2;
+}
 
+# Get help and version information.
 help=$(grep "^##?" "$0" | cut -c 5-)
 version=$(grep "^#?"  "$0" | cut -c 4-)
+
+# Parse arguments.
 parsed="$(docopts -h "$help" -V "$version" : "$@")"
 eval "$parsed"
 
 # Extract the file extension and basename.
-BASENAME=$(basename -- "$FILE")
-EXTENSION="${BASENAME##*.}"
-BASENAME="${BASENAME%.*}"
+basename=$(basename -- "$FILE")
+extension="${basename##*.}"
+basename="${basename%.*}"
 
 # Define the backup file name.
-NEWFILE="$BASENAME.bak.$EXTENSION"
+new_file="$basename.bak.$extension"
 
 if [[ "$rename" == "true" ]]; then
     # If the rename option is provided, rename the file instead of copying it.
-    if confirm_overwrite "$NEWFILE"; then
-        mv "$FILE" "$NEWFILE" \
-            && printf "File renamed from %s to %s.\n" "$FILE" "$NEWFILE"
+    if confirm_overwrite "$new_file"; then
+        mv "$FILE" "$new_file";
+        printf "File renamed from %s to %s.\n" "$FILE" "$new_file";
     fi
 else
     # Copy the file.
-    if confirm_overwrite "$NEWFILE"; then
-        cp "$FILE" "$NEWFILE" \
-            && printf "File copied from %s to %s.\n" "$FILE" "$NEWFILE"
+    if confirm_overwrite "$new_file"; then
+        cp "$FILE" "$new_file";
+        printf "File copied from %s to %s.\n" "$FILE" "$new_file";
     fi
 fi
