Update error message

diff --git a/bin/bak b/bin/bak
--- a/bin/bak
+++ b/bin/bak
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 
-#? bak, Time-stamp: <2024-02-06 Tue 11:03>
+#? bak, Time-stamp: <2024-05-28 Tue 11:27>
 #? Copyright (C) 2020-2024 Fabrice Niessen
 #?
 #? License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
@@ -42,9 +42,9 @@ confirm_overwrite() {
     fi
 }
 
-# Check if docopts command is available.
+# Check if 'docopts' command is available.
 if ! command -v docopts > /dev/null 2>&1; then
-    printf >&2 'Error: docopts command not found.\n'
+    printf >&2 "Error: 'docopts' command not found.\n"
     exit 2
 fi
 
@@ -77,7 +77,7 @@ new_file="$(dirname -- "$FILE")/$basename$BAK_EXTENSION$extension"
 
 # Check if the input file exists.
 if [[ ! -f "$FILE" ]]; then
-    printf >&2 "ERROR: Input file '%s' does not exist.\n" "$FILE"
+    printf >&2 "Error: Input file '%s' does not exist.\n" "$FILE"
     exit 2
 fi
 
diff --git a/bin/unbak b/bin/unbak
--- a/bin/unbak
+++ b/bin/unbak
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 
-#? unbak, Time-stamp: <2024-02-02 Fri 14:52>
+#? unbak, Time-stamp: <2024-05-28 Tue 11:22>
 #? Copyright (C) 2020-2024 Fabrice Niessen
 #?
 #? License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
@@ -24,9 +24,9 @@
 # Set -uo pipefail for undefined variable check and pipeline failure propagation.
 set -uo pipefail
 
-# Check if docopts command is available.
+# Check if 'docopts' command is available.
 if ! command -v docopts > /dev/null 2>&1; then
-    printf >&2 'Error: docopts command not found.\n'
+    printf >&2 "Error: 'docopts' command not found.\n"
     exit 2
 fi
 
@@ -46,7 +46,7 @@ readonly BAK_EXTENSION="_bak"
 
 # Check if the backed-up file exists.
 if [[ ! -f "$FILE" ]]; then
-    printf >&2 "ERROR: Backed-up file '%s' does not exist.\n" "$FILE"
+    printf >&2 "Error: Backed-up file '%s' does not exist.\n" "$FILE"
     exit 2
 fi
 
@@ -80,7 +80,8 @@ fi
 # Restore the original file to its original path.
 original_directory=$(dirname -- "$FILE")
 mv "$FILE" "$original_directory/$original_file_with_extension"
-printf "File restored from %s to %s/%s.\n" "$FILE" "$original_directory" "$original_file_with_extension"
+printf "File restored from %s to %s/%s.\n" \
+       "$FILE" "$original_directory" "$original_file_with_extension"
 
 # Exit with a success code.
 exit 0
