Improve error formatting with reusable color variables

diff --git a/bin/bak b/bin/bak
--- a/bin/bak
+++ b/bin/bak
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 
-#? bak, Time-stamp: <2025-06-20 Fri 10:17>
+#? bak, Time-stamp: <2025-06-20 Fri 10:51>
 #? Copyright (C) 2020-2025 Fabrice Niessen. All rights reserved.
 #?
 #? License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
@@ -32,11 +32,14 @@ EX_OSERR=71
 # Set -uo pipefail for undefined variable check and pipeline failure propagation.
 set -uo pipefail
 
-# Define tput formatting variables for reuse.
-BOLD=$(tput bold)
-GREEN=$(tput setaf 2)
-RED=$(tput setaf 1)
+# Define color and formatting variables.
 RESET=$(tput sgr0)
+BOLD=$(tput bold)
+RED=$(tput setaf 1)
+GREEN=$(tput setaf 2)
+WHITE=$(tput setaf 7)
+RED_BG=$(tput setab 1)
+ERROR="${BOLD}${WHITE}${RED_BG}"
 
 # Check if 'colordiff' is installed, and use it for colorized output, fallback
 # to 'diff'.
@@ -73,8 +76,8 @@ confirm_overwrite_or_skip() {
 
 # Check if 'docopts' command is available.
 if ! command -v docopts > /dev/null 2>&1; then
-    printf >&2 "Error: 'docopts' command not found.\n"
-    exit $EX_UNAVAILABLE
+    printf >&2 "${ERROR}ERROR: 'docopts' command not found.${RESET}\n"
+    exit $EX_UNAVAILABLE                # Service unavailable.
 fi
 
 # Extract help and version information from the script.
