Improve check for available command

diff --git a/bin/cate b/bin/cate
--- a/bin/cate
+++ b/bin/cate
@@ -3,7 +3,10 @@
 # Print the contents of the current buffer in Emacs to the terminal.
 
 # Check if emacsclient command is available.
-command -v emacsclient > /dev/null 2>&1 || { printf >&2 'Error: emacsclient command not found.\n'; exit 2; }
+if ! command -v emacsclient > /dev/null 2>&1; then
+    printf >&2 'Error: emacsclient command not found.\n'
+    exit 2
+fi
 
 fifo="$(mktemp -u)"
 mkfifo "$fifo"
