Fix error with 'set -e' (must be set after docopts)

diff --git a/bin/f b/bin/f
--- a/bin/f
+++ b/bin/f
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 
-#? f, Time-stamp: <2024-01-04 Thu 17:49>
+#? f, Time-stamp: <2024-02-06 Tue 09:03>
 #? Copyright (C) 2020-2024 Fabrice Niessen
 #?
 #? License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
@@ -25,7 +25,8 @@
 ##?   f                             list all directories and files
 ##?   f doc                         list directories or files matching doc in their name
 
-set -euo pipefail
+# Set -uo pipefail for undefined variable check and pipeline failure propagation.
+set -uo pipefail
 
 # Check if docopts command is available.
 if ! command -v docopts > /dev/null 2>&1; then
@@ -40,6 +41,9 @@ version=$(grep "^#?" "$0" | cut -c 4-)
 # Get command-line arguments.
 args="$(docopts -h "$help" -V "$version" : "$@")"
 eval "$args"
+
+# Set -e to exit on non-zero command status.
+set -e
 
 # Set color codes for formatting.
 readonly MATCH_COLOR="1;37;1;44"        # White text on blue background.
