Refactor code

diff --git a/bin/f b/bin/f
--- a/bin/f
+++ b/bin/f
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 
-#? f, Time-stamp: <2023-02-04 Sat 16:11>
+#? f, Time-stamp: <2023-05-13 Sat 21:06>
 #? Copyright (C) 2020-2023 Fabrice Niessen
 #?
 #? License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
@@ -23,11 +23,18 @@
 ##?   f doc                         list directories or files matching doc in their name
 
 # Check if docopts command is available.
-command -v docopts > /dev/null 2>&1 || { printf >&2 'Error: docopts command not found.\n'; exit 2; }
+if ! command -v docopts > /dev/null 2>&1; then
+    printf >&2 'Error: docopts command not found.\n'
+    exit 2
+fi
 
+# Get help and version information.
 help=$(grep "^##?" "$0" | cut -c 5-)
 version=$(grep "^#?"  "$0" | cut -c 4-)
+
+# Parse arguments.
 parsed="$(docopts -h "$help" -V "$version" : "$@")"
 eval "$parsed"
 
-find . -iname "*$PATTERN*" -printf '%P\n' | grep -i --color=auto "$PATTERN"
+# Find all directories or files matching the PATTERN.
+find . -iname "*$PATTERN*" -printf '%P\n' 2>/dev/null | grep -i --color=auto "$PATTERN"
