Fix error with 'set -e' (must be set after docopts)

diff --git a/bin/find-recent-files b/bin/find-recent-files
--- a/bin/find-recent-files
+++ b/bin/find-recent-files
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 
-#? find-recent-files, Time-stamp: <2024-01-05 Fri 15:40>
+#? find-recent-files, Time-stamp: <2024-02-06 Tue 08:58>
 #? Copyright (C) 2023-2024 Fabrice Niessen
 #?
 #? License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
@@ -19,7 +19,8 @@
 ##?   -h, --help                    display this help and exit
 ##?   -V, --version                 display version information and exit
 
-set -euo pipefail
+# Set -uo pipefail for undefined variable check and pipeline failure propagation.
+set -uo pipefail
 
 # Check if docopts command is available.
 if ! command -v docopts > /dev/null 2>&1; then
@@ -34,6 +35,9 @@ version=$(grep "^#?" "$0" | cut -c 4-)
 # Get command-line arguments.
 args="$(docopts -h "$help" -V "$version" : "$@")"
 eval "$args"
+
+# Set -e to exit on non-zero command status.
+set -e
 
 # Set the default directory if not provided.
 readonly DIRECTORY=${DIRECTORY:-.}
