Add 'set' options and improve doc/variable names

diff --git a/bin/find-recently-modified-files b/bin/find-recently-modified-files
--- a/bin/find-recently-modified-files
+++ b/bin/find-recently-modified-files
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 
-#? find-recently-modified-files, Time-stamp: <2023-06-12 Mon 10:35>
+#? find-recently-modified-files, Time-stamp: <2023-07-31 Mon 10:50>
 #? Copyright (C) 2023 Fabrice Niessen
 #?
 #? License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
@@ -19,13 +19,21 @@
 ##?   -h, --help                    display this help and exit
 ##?   -V, --version                 display version information and exit
 
-# Check if docopts command is available.
-command -v docopts > /dev/null 2>&1 || { printf >&2 'Error: docopts command not found.\n'; exit 2; }
+set -euo pipefail
 
+# Check if docopts command is available.
+if ! command -v docopts > /dev/null 2>&1; then
+    printf >&2 'Error: docopts command not found.\n'
+    exit 2
+fi
+
+# Extract help and version information from the script.
 help=$(grep "^##?" "$0" | cut -c 5-)
 version=$(grep "^#?" "$0" | cut -c 4-)
-parsed="$(docopts -h "$help" -V "$version" : "$@")"
-eval "$parsed"
+
+# Get command-line arguments.
+args="$(docopts -h "$help" -V "$version" : "$@")"
+eval "$args"
 
 DIRECTORY=${DIRECTORY:-.}
 
