Add validation for numeric THRESHOLD in find-recent-files script
Added an error message and exit code if the THRESHOLD is not numeric.

diff --git a/bin/find-recent-files b/bin/find-recent-files
--- a/bin/find-recent-files
+++ b/bin/find-recent-files
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 
-#? find-recent-files, Time-stamp: <2024-05-17 Fri 17:12>
+#? find-recent-files, Time-stamp: <2024-05-17 Fri 17:21>
 #? Copyright (C) 2023-2024 Fabrice Niessen
 #?
 #? License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
@@ -42,6 +42,12 @@ set -e
 
 # Set the threshold, defaulting to 7 if not provided.
 readonly THRESHOLD=${THRESHOLD:-7}
+
+# Validate that THRESHOLD is a numeric value.
+if ! [[ "$THRESHOLD" =~ ^[0-9]+$ ]]; then
+    printf >&2 'Error: THRESHOLD must be a numeric value.\n'
+    exit 2
+fi
 
 # Set the default directory if not provided.
 readonly DIRECTORY=${DIRECTORY:-.}
