Add print format

diff --git a/bin/find-today-files b/bin/find-today-files
--- a/bin/find-today-files
+++ b/bin/find-today-files
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 
-#? find-today-files, Time-stamp: <2023-02-01 Wed 13:39>
+#? find-today-files, Time-stamp: <2023-02-06 Mon 13:23>
 #? Copyright (C) 2023 Fabrice Niessen
 #?
 #? License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
@@ -19,7 +19,9 @@
 ##?   -h, --help                    display this help and exit
 ##?   -V, --version                 display version information and exit
 
-command -v docopts > /dev/null 2>&1 || { printf >&2 'docopts not found\n'; exit 2; }
+# Check if docopts command is available.
+command -v docopts > /dev/null 2>&1 || { printf >&2 'Error: docopts command not found.\n'; exit 2; }
+
 help=$(grep "^##?" "$0" | cut -c 5-)
 version=$(grep "^#?"  "$0" | cut -c 4-)
 parsed="$(docopts -h "$help" -V "$version" : "$@")"
@@ -27,8 +29,9 @@ eval "$parsed"
 
 DIRECTORY=${DIRECTORY:=.}
 
+# List all files modified TODAY only (since start of day only, i.e. 00:00).
 if [ -n "$EXTENSION" ]; then
-    find "$DIRECTORY" -type f -name "*.$EXTENSION" -daystart -mtime 0
+    find "$DIRECTORY" -type f -name "*.$EXTENSION" -daystart -mtime 0 -printf "  %CY-%Cm-%Cd %Ca %CH:%CM - %P\n"
 else
-    find "$DIRECTORY" -type f -daystart -mtime 0
+    find "$DIRECTORY" -type f -daystart -mtime 0 -printf "  %CY-%Cm-%Cd %Ca %CH:%CM - %P\n"
 fi
