Clarify script comment

diff --git a/bin/find-big-files b/bin/find-big-files
--- a/bin/find-big-files
+++ b/bin/find-big-files
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 
-#? find-big-files, Time-stamp: <2024-04-02 Tue 10:04>
+#? find-big-files, Time-stamp: <2024-05-28 Tue 11:16>
 #? Copyright (C) 2023-2024 Fabrice Niessen. All rights reserved.
 #?
 #? License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
@@ -18,9 +18,9 @@
 # Set -uo pipefail for undefined variable check and pipeline failure propagation.
 set -uo pipefail
 
-# Check if docopts command is available.
+# Check if 'docopts' command is available.
 if ! command -v docopts > /dev/null 2>&1; then
-    printf >&2 'Error: docopts command not found.\n'
+    printf >&2 "Error: 'docopts' command not found.\n"
     exit 2
 fi
 
diff --git a/bin/find-common-lines b/bin/find-common-lines
--- a/bin/find-common-lines
+++ b/bin/find-common-lines
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 
-#? find-common-lines, Time-stamp: <2024-05-21 Tue 13:55>
+#? find-common-lines, Time-stamp: <2024-05-28 Tue 11:19>
 #? Copyright (C) 2024 Fabrice Niessen. All rights reserved.
 #?
 #? License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
@@ -22,9 +22,9 @@
 # Set -uo pipefail for undefined variable check and pipeline failure propagation.
 set -uo pipefail
 
-# Check if docopts command is available.
+# Check if 'docopts' command is available.
 if ! command -v docopts > /dev/null 2>&1; then
-    printf >&2 'Error: docopts command not found.\n'
+    printf >&2 "Error: 'docopts' command not found.\n"
     exit 2
 fi
 
@@ -53,9 +53,9 @@ if [ ! -f "$FILE1" ] || [ ! -f "$FILE2" ]; then
     exit 2
 fi
 
-# Check if dos2unix is available.
+# Check if 'dos2unix' command is available.
 if ! command -v dos2unix &>/dev/null; then
-    printf >&2 "Error: dos2unix is not installed or not found in PATH.\n"
+    printf >&2 "Error: 'dos2unix' is not installed or not found in PATH.\n"
     exit 2
 fi
 
