Add directory and extension options

diff --git a/bin/find-today-files b/bin/find-today-files
--- a/bin/find-today-files
+++ b/bin/find-today-files
@@ -1,8 +1,34 @@
 #!/usr/bin/env bash
 
-# Get the current date in the format YYYY-MM-DD.
-today=$(date +%Y-%m-%d)
+#? find-today-files, Time-stamp: <2023-02-01 Wed 13:39>
+#? Copyright (C) 2023 Fabrice Niessen
+#?
+#? License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
+#? This is free software: you are free to change and redistribute it.
+#? There is NO WARRANTY, to the extent permitted by law.
 
-# Find all files in the current directory and its subdirectories that have
-# today's date in the modification time.
-find . -type f -name "*" -mtime 0 -print
+##? Usage: find-today-files [options] [DIRECTORY]
+##?
+##? Find all files modified today in a specified directory, filtered by extension.
+##?
+##? Arguments:
+##?   DIRECTORY                     starting directory
+##?
+##? Options:
+##?   -e, --extension=EXTENSION     filter files by extension
+##?   -h, --help                    display this help and exit
+##?   -V, --version                 display version information and exit
+
+command -v docopts > /dev/null 2>&1 || { printf >&2 'docopts not found\n'; exit 2; }
+help=$(grep "^##?" "$0" | cut -c 5-)
+version=$(grep "^#?"  "$0" | cut -c 4-)
+parsed="$(docopts -h "$help" -V "$version" : "$@")"
+eval "$parsed"
+
+DIRECTORY=${DIRECTORY:=.}
+
+if [ -n "$EXTENSION" ]; then
+    find "$DIRECTORY" -type f -name "*.$EXTENSION" -daystart -mtime 0
+else
+    find "$DIRECTORY" -type f -daystart -mtime 0
+fi
