Clarify script comment

diff --git a/bin/find-duplicate-filenames1 b/bin/find-duplicate-filenames1
--- a/bin/find-duplicate-filenames1
+++ b/bin/find-duplicate-filenames1
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 
-#? find-duplicate-filenames1, Time-stamp: <2024-05-23 Thu 11:42>
+#? find-duplicate-filenames1, Time-stamp: <2024-05-28 Tue 11:15>
 #? Copyright (C) 2024 Fabrice Niessen. All rights reserved.
 #?
 #? License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
@@ -22,9 +22,9 @@
 # Set -uo pipefail for undefined variable check and pipeline failure propagation.
 set -uo pipefail
 
-# Check if docopts command is available.
+# Check if 'docopts' command is available.
 if ! command -v docopts > /dev/null 2>&1; then
-    printf >&2 'Error: docopts command not found.\n'
+    printf >&2 "Error: 'docopts' command not found.\n"
     exit 2
 fi
 
diff --git a/bin/find-empty-files b/bin/find-empty-files
--- a/bin/find-empty-files
+++ b/bin/find-empty-files
@@ -18,9 +18,9 @@
 # Set -uo pipefail for undefined variable check and pipeline failure propagation.
 set -uo pipefail
 
-# Check if docopts command is available.
+# Check if 'docopts' command is available.
 if ! command -v docopts > /dev/null 2>&1; then
-    printf >&2 'Error: docopts command not found.\n'
+    printf >&2 "Error: 'docopts' command not found.\n"
     exit 2
 fi
 
