Update `find-common-lines` script to use docopts
- Added licensing information and header comments.
- Implemented `docopts` for argument parsing.
- Added `set -uo pipefail` for better error detection.

diff --git a/bin/find-common-lines b/bin/find-common-lines
--- a/bin/find-common-lines
+++ b/bin/find-common-lines
@@ -1,5 +1,44 @@
 #!/usr/bin/env bash
 
+#? find-common-lines, Time-stamp: <2024-05-17 Fri 10:50>
+#? Copyright (C) 2024 Fabrice Niessen. All rights reserved.
+#?
+#? License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
+#? This is free software: you are free to change and redistribute it.
+#? There is NO WARRANTY, to the extent permitted by law.
+
+##? Usage: find-common-lines [options] FILE1 FILE2
+##?
+##? Find common lines between two files.
+##?
+##? Arguments:
+##?   FILE1                         Path to the first file.
+##?   FILE2                         Path to the second file.
+##?
+##? Options:
+##?   -h, --help                    Display this help and exit.
+##?   -V, --version                 Show version.
+
+# Set -uo pipefail for undefined variable check and pipeline failure propagation.
+set -uo pipefail
+
+# Check if docopts command is available.
+if ! command -v docopts > /dev/null 2>&1; then
+    printf >&2 'Error: docopts command not found.\n'
+    exit 2
+fi
+
+# Extract help and version information from the script.
+help=$(grep "^##?" "$0" | cut -c 5-)
+version=$(grep "^#?" "$0" | cut -c 4-)
+
+# Get command-line arguments.
+args="$(docopts -h "$help" -V "$version" : "$@")"
+eval "$args"
+
+# Set -e to exit on non-zero command status.
+set -e
+
 cleanup() {
     # Remove temporary files.
     rm -f "$temp_file1" "$temp_file2"
@@ -7,15 +46,8 @@ cleanup() {
 
 trap cleanup INT
 
-if [ $# -ne 2 ]; then
-    printf >&2 "Usage: %s file1 file2\n" "$0"
-    exit 2
-fi
-
-file1="$1"
-file2="$2"
-
-if [ ! -f "$file1" ] || [ ! -f "$file2" ]; then
+# Check if files exist.
+if [ ! -f "$FILE1" ] || [ ! -f "$FILE2" ]; then
     printf >&2 "Error: Both files must exist.\n"
     exit 2
 fi
@@ -31,8 +63,8 @@ temp_file1=$(mktemp)
 temp_file2=$(mktemp)
 
 # Copy the content of the original files to the temporary files.
-cp "$file1" "$temp_file1"
-cp "$file2" "$temp_file2"
+cp "$FILE1" "$temp_file1"
+cp "$FILE2" "$temp_file2"
 
 # Convert temporary files to Unix format.
 dos2unix "$temp_file1" "$temp_file2" >/dev/null 2>&1
