Fix error with 'set -e' (must be set after docopts)

diff --git a/bin/multi-directory-file-access-list-unaccessed-directories b/bin/multi-directory-file-access-list-unaccessed-directories
--- a/bin/multi-directory-file-access-list-unaccessed-directories
+++ b/bin/multi-directory-file-access-list-unaccessed-directories
@@ -1,7 +1,7 @@
 #!/usr/bin/env bash
 
-#? file-access-list-unaccessed-directories, Time-stamp: <2023-10-24 Tue 10:15>
-#? Copyright (C) 2023 Fabrice Niessen. All rights reserved.
+#? file-access-list-unaccessed-directories, Time-stamp: <2024-02-06 Tue 10:56>
+#? Copyright (C) 2023-2024 Fabrice Niessen. All rights reserved.
 #?
 #? License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
 #? This is free software: you are free to change and redistribute it.
@@ -19,7 +19,8 @@
 ##?   -h, --help                    Display this help and exit.
 ##?   -V, --version                 Show version.
 
-set -euo pipefail
+# Set -uo pipefail for undefined variable check and pipeline failure propagation.
+set -uo pipefail
 
 # Check if docopts command is available.
 if ! command -v docopts > /dev/null 2>&1; then
@@ -34,6 +35,9 @@ version=$(grep "^#?" "$0" | cut -c 4-)
 # Get command-line arguments.
 args="$(docopts -h "$help" -V "$version" : "$@")"
 eval "$args"
+
+# Set -e to exit on non-zero command status.
+set -e
 
 # Set a default log file if no argument is provided.
 LOG_FILE="${LOG_FILE:-file_access_log.txt}"
