Clarify script comment

diff --git a/bin/multi-directory-file-access-monitor b/bin/multi-directory-file-access-monitor
--- a/bin/multi-directory-file-access-monitor
+++ b/bin/multi-directory-file-access-monitor
@@ -22,9 +22,9 @@
 # Set -uo pipefail for undefined variable check and pipeline failure propagation.
 set -uo pipefail
 
-# Check if docopts command is available.
+# Check if 'docopts' command is available.
 if ! command -v docopts > /dev/null 2>&1; then
-    printf >&2 'Error: docopts command not found.\n'
+    printf >&2 "Error: 'docopts' command not found.\n"
     exit 2
 fi
 
@@ -39,7 +39,7 @@ eval "$args"
 # Set -e to exit on non-zero command status.
 set -e
 
-# Check if inotifywait command is available.
+# Check if 'inotifywait' command is available.
 if ! command -v inotifywait > /dev/null 2>&1; then
     printf >&2 "Error: 'inotifywait' command not found. Please install inotify-tools.\n"
     exit 2
diff --git a/bin/remove-matching-lines-between-files b/bin/remove-matching-lines-between-files
--- a/bin/remove-matching-lines-between-files
+++ b/bin/remove-matching-lines-between-files
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 
-#? remove-matching-lines-between-files, Time-stamp: <2024-02-06 Tue 09:00>
+#? remove-matching-lines-between-files, Time-stamp: <2024-05-28 Tue 11:18>
 #? Copyright (C) 2020-2024 Fabrice Niessen
 #?
 #? License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
@@ -22,9 +22,9 @@
 # Set -uo pipefail for undefined variable check and pipeline failure propagation.
 set -uo pipefail
 
-# Check if docopts command is available.
+# Check if 'docopts' command is available.
 if ! command -v docopts > /dev/null 2>&1; then
-    printf >&2 'Error: docopts command not found.\n'
+    printf >&2 "Error: 'docopts' command not found.\n"
     exit 2
 fi
 
@@ -41,12 +41,12 @@ set -e
 
 # Check that both files exist.
 if [[ ! -f "$FILE_A" ]]; then
-    printf "Error: %s does not exist\n" "$FILE_A" >&2
+    printf >&2 "Error: '%s' does not exist\n" "$FILE_A"
     exit 2
 fi
 
 if [[ ! -f "$FILE_B" ]]; then
-    printf "Error: %s does not exist\n" "$FILE_B" >&2
+    printf >&2 "Error: '%s' does not exist\n" "$FILE_B"
     exit 2
 fi
 
diff --git a/bin/remove-zone-identifier-files b/bin/remove-zone-identifier-files
--- a/bin/remove-zone-identifier-files
+++ b/bin/remove-zone-identifier-files
@@ -18,9 +18,9 @@
 # Set -uo pipefail for undefined variable check and pipeline failure propagation.
 set -uo pipefail
 
-# Check if docopts command is available.
+# Check if 'docopts' command is available.
 if ! command -v docopts > /dev/null 2>&1; then
-    printf >&2 'Error: docopts command not found.\n'
+    printf >&2 "Error: 'docopts' command not found.\n"
     exit 2
 fi
 
@@ -44,9 +44,9 @@ if [[ ! -d "$directory_path" ]]; then
     exit 1
 fi
 
-# Check if getfattr command is available.
+# Check if 'getfattr' command is available.
 if ! command -v getfattr &> /dev/null; then
-    printf "Error: 'getfattr' command not found. Please install the 'attr' package.\n"
+    printf >&2 "Error: 'getfattr' command not found. Please install the 'attr' package.\n"
     exit 2
 fi
 
diff --git a/bin/replace-in-directory b/bin/replace-in-directory
--- a/bin/replace-in-directory
+++ b/bin/replace-in-directory
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 
-#? replace-in-directory, Time-stamp: <2024-02-06 Tue 08:57>
+#? replace-in-directory, Time-stamp: <2024-05-28 Tue 11:21>
 #? Copyright (C) 2020-2024 Fabrice Niessen
 #?
 #? License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
@@ -24,9 +24,9 @@
 # Set -uo pipefail for undefined variable check and pipeline failure propagation.
 set -uo pipefail
 
-# Check if docopts command is available.
+# Check if 'docopts' command is available.
 if ! command -v docopts > /dev/null 2>&1; then
-    printf >&2 'Error: docopts command not found.\n'
+    printf >&2 "Error: 'docopts' command not found.\n"
     exit 2
 fi
 
@@ -43,7 +43,7 @@ set -e
 
 # Check if directory exists.
 if [[ ! -d "$DIRECTORY" ]]; then
-    echo "Error: $DIRECTORY is not a directory."
+    printf >&2 "Error: '%s' is not a directory.\n" "$DIRECTORY"
     exit 2
 fi
 
@@ -63,7 +63,7 @@ num_files=$(find "$DIRECTORY" -type f | wc -l)
 curr_file=1
 for file in "$DIRECTORY"/*; do
     if [[ -f "$file" ]]; then
-        echo "Processing file $curr_file of $num_files: $file"
+        printf "Processing file %d of %d: %s\n" "$curr_file" "$num_files" "$file"
         sed -i "$sed_args" "$file"
         ((curr_file++))
     fi
diff --git a/bin/uncolor b/bin/uncolor
--- a/bin/uncolor
+++ b/bin/uncolor
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 
-#? uncolor, Time-stamp: <2024-02-06 Tue 08:57>
+#? uncolor, Time-stamp: <2024-05-28 Tue 11:14>
 #? Copyright (C) 2020-2024 Fabrice Niessen
 #?
 #? License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
@@ -21,9 +21,9 @@
 # Set -uo pipefail for undefined variable check and pipeline failure propagation.
 set -uo pipefail
 
-# Check if docopts command is available.
+# Check if 'docopts' command is available.
 if ! command -v docopts > /dev/null 2>&1; then
-    printf >&2 'Error: docopts command not found.\n'
+    printf >&2 "Error: 'docopts' command not found.\n"
     exit 2
 fi
 
