Fix error with 'set -e' (must be set after docopts)

diff --git a/bin/remove-matching-lines-between-files b/bin/remove-matching-lines-between-files
--- a/bin/remove-matching-lines-between-files
+++ b/bin/remove-matching-lines-between-files
@@ -1,7 +1,7 @@
 #!/usr/bin/env bash
 
-#? remove-matching-lines-between-files, Time-stamp: <2023-07-31 Mon 10:38>
-#? Copyright (C) 2020-2023 Fabrice Niessen
+#? remove-matching-lines-between-files, Time-stamp: <2024-02-06 Tue 09:00>
+#? Copyright (C) 2020-2024 Fabrice Niessen
 #?
 #? License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
 #? This is free software: you are free to change and redistribute it.
@@ -19,7 +19,8 @@
 ##?   -h, --help                    display this help and exit
 ##?   -V, --version                 display version information and exit
 
-set -euo pipefail
+# Set -uo pipefail for undefined variable check and pipeline failure propagation.
+set -uo pipefail
 
 # Check if docopts command is available.
 if ! command -v docopts > /dev/null 2>&1; then
@@ -34,6 +35,9 @@ version=$(grep "^#?" "$0" | cut -c 4-)
 # Get command-line arguments.
 args="$(docopts -h "$help" -V "$version" : "$@")"
 eval "$args"
+
+# Set -e to exit on non-zero command status.
+set -e
 
 # Check that both files exist.
 if [[ ! -f "$FILE_A" ]]; then
