Fix error with 'set -e' (must be set after docopts)

diff --git a/bin/remove-zone-identifier-files b/bin/remove-zone-identifier-files
--- a/bin/remove-zone-identifier-files
+++ b/bin/remove-zone-identifier-files
@@ -1,7 +1,7 @@
 #!/usr/bin/env bash
 
 #? remove-zone-identifier-files, Time-stamp: 20220204.1026
-#? Copyright (C) 2023 Fabrice Niessen
+#? Copyright (C) 2023-2024 Fabrice Niessen
 #?
 #? License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
 #? This is free software: you are free to change and redistribute it.
@@ -15,7 +15,8 @@
 ##?   -h, --help                    display this help and exit
 ##?   -V, --version                 display version information and exit
 
-set -euo pipefail
+# Set -uo pipefail for undefined variable check and pipeline failure propagation.
+set -uo pipefail
 
 # Check if docopts command is available.
 if ! command -v docopts > /dev/null 2>&1; then
@@ -30,6 +31,9 @@ version=$(grep "^#?" "$0" | cut -c 4-)
 # Get command-line arguments.
 args="$(docopts -h "$help" -V "$version" : "$@")"
 eval "$args"
+
+# Set -e to exit on non-zero command status.
+set -e
 
 # Directory path where Zone.Identifier files will be removed.
 directory_path="."
