Add 'set' options and improve doc/variable names

diff --git a/bin/replace-in-directory b/bin/replace-in-directory
--- a/bin/replace-in-directory
+++ b/bin/replace-in-directory
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 
-#? replace-in-directory, Time-stamp: <2023-06-12 Mon 10:35>
+#? replace-in-directory, Time-stamp: <2023-07-31 Mon 10:50>
 #? Copyright (C) 2020-2023 Fabrice Niessen
 #?
 #? License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
@@ -21,19 +21,21 @@
 ##?   -h, --help                    Show this help message and exit.
 ##?   -V, --version                 Show version.
 
+set -euo pipefail
+
 # Check if docopts command is available.
 if ! command -v docopts > /dev/null 2>&1; then
-    printf >&2 'Error: "docopts" command not found.\n'
+    printf >&2 'Error: docopts command not found.\n'
     exit 2
 fi
 
-# Get help and version information.
+# Extract help and version information from the script.
 help=$(grep "^##?" "$0" | cut -c 5-)
 version=$(grep "^#?" "$0" | cut -c 4-)
 
-# Parse arguments.
-parsed="$(docopts -h "$help" -V "$version" : "$@")"
-eval "$parsed"
+# Get command-line arguments.
+args="$(docopts -h "$help" -V "$version" : "$@")"
+eval "$args"
 
 # Check if directory exists.
 if [[ ! -d "$DIRECTORY" ]]; then
