Fix error with 'set -e' (must be set after docopts)

diff --git a/bin/swap b/bin/swap
--- a/bin/swap
+++ b/bin/swap
@@ -1,7 +1,7 @@
 #!/usr/bin/env bash
 
-#? swap, Time-stamp: <2023-12-27 Wed 10:53>
-#? Copyright (C) 2020-2023 Fabrice Niessen
+#? swap, Time-stamp: <2024-02-06 Tue 09:00>
+#? Copyright (C) 2020-2024 Fabrice Niessen
 #?
 #? License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
 #? This is free software: you are free to change and redistribute it.
@@ -22,7 +22,8 @@
 ##? Examples:
 ##?   swap config config.bak        swap files config and config.bak
 
-set -euo pipefail
+# Set -uo pipefail for undefined variable check and pipeline failure propagation.
+set -uo pipefail
 
 # Check if docopts command is available.
 if ! command -v docopts > /dev/null 2>&1; then
@@ -37,6 +38,9 @@ version=$(grep "^#?" "$0" | cut -c 4-)
 # Get command-line arguments.
 args="$(docopts -h "$help" -V "$version" : "$@")"
 eval "$args"
+
+# Set -e to exit on non-zero command status.
+set -e
 
 # Use a temporary file to perform the swap.
 temporary_file=$(mktemp "${TMP:-/tmp}/swap.XXXXXXXXXX")
