Refactor code

diff --git a/bin/swap b/bin/swap
--- a/bin/swap
+++ b/bin/swap
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 
-#? swap, Time-stamp: <2023-04-06 Thu 11:51>
+#? swap, Time-stamp: <2023-05-12 Fri 12:13>
 #? Copyright (C) 2020-2023 Fabrice Niessen
 #?
 #? License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
@@ -23,14 +23,20 @@
 ##?   swap config config.bak        swap files config and config.bak
 
 # Check if docopts command is available.
-command -v docopts > /dev/null 2>&1 || { printf >&2 'Error: docopts command not found.\n'; exit 2; }
+if ! command -v docopts > /dev/null 2>&1; then
+    printf >&2 'Error: docopts command not found.\n'
+    exit 2
+fi
 
+# Get help and version information.
 help=$(grep "^##?" "$0" | cut -c 5-)
 version=$(grep "^#?"  "$0" | cut -c 4-)
+
+# Parse arguments.
 parsed="$(docopts -h "$help" -V "$version" : "$@")"
 eval "$parsed"
 
 tmpfile=$(mktemp ${TMP:-/tmp}/swap.XXXXXXXXXX)
-mv -f "$FILE1" "$tmpfile" \
-    && mv -f "$FILE2" "$FILE1" \
-    && mv -f "$tmpfile" "$FILE2"
+mv -f "$FILE1" "$tmpfile"
+mv -f "$FILE2" "$FILE1"
+mv -f "$tmpfile" "$FILE2"
