Handle command parameters for the command to execute 100 times

diff --git a/bin/time-run-command-100 b/bin/time-run-command-100
--- a/bin/time-run-command-100
+++ b/bin/time-run-command-100
@@ -1,13 +1,18 @@
 #!/usr/bin/env bash
 
-# Usage: time-run-command-100 [options] COMMAND
+# Usage: time-run-command-100 [options] COMMAND [PARAMETERS...]
 #
 # Run a command 100 times and print its average and median execution time.
 
 # Get the command to run.
-command="$1"
+command=("$1")
+shift
 
-printf "Command: %s\n" "$command"
+printf "Command: %s " "${command[*]}"
+for arg in "$@"; do
+    printf "'%s' " "$arg"
+done
+printf "\n"
 
 # Create an array to store the execution times in hundredths of a second.
 execution_times=()
@@ -15,13 +20,21 @@ execution_times=()
 # Run the command 100 times and store the execution times.
 for i in {1..100}; do
     start_time=$(date +%s%N) # Current time in nanoseconds.
-    $command > /dev/null 2>&1 # Run the command and discard output.
+    "${command[@]}" "$@" > /dev/null 2>&1 # Run the command and discard output.
+    # exit_code=$?
     end_time=$(date +%s%N)
 
     # Calculate execution time in hundredths of a second.
     execution_time_hundredths=$(( (end_time - start_time + 5000000) / 10000000 ))
 
     execution_times+=($execution_time_hundredths)
+
+    # # Print the executed command and its exit code.
+    # printf "Run %d: %s " "$i" "${command[*]}"
+    # for arg in "$@"; do
+    #     printf "'%s' " "$arg"
+    # done
+    # printf "(Exit Code: %d)\n" "$exit_code"
 
     # Print a dot for each command run.
     printf "."
@@ -52,7 +65,7 @@ median_execution_time_seconds=$((median_execution_time / 100))
 median_execution_time_hundredths=$((median_execution_time % 100))
 
 # Print the results.
-printf "Average execution time: %d.%02ds\n" \
-    $average_execution_time_seconds $average_execution_time_hundredths
+printf "\nAverage execution time: %d.%02ds\n" \
+       $average_execution_time_seconds $average_execution_time_hundredths
 printf "Median execution time: %d.%02ds\n" \
-    $median_execution_time_seconds $median_execution_time_hundredths
+       $median_execution_time_seconds $median_execution_time_hundredths
