Fix error with 'set -e' (must be set after docopts)

diff --git a/bin/unbak b/bin/unbak
--- a/bin/unbak
+++ b/bin/unbak
@@ -1,7 +1,7 @@
 #!/usr/bin/env bash
 
-#? unbak, Time-stamp: <2023-12-27 Wed 11:12>
-#? Copyright (C) 2020-2023 Fabrice Niessen
+#? unbak, Time-stamp: <2024-02-02 Fri 14:52>
+#? Copyright (C) 2020-2024 Fabrice Niessen
 #?
 #? License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
 #? This is free software: you are free to change and redistribute it.
@@ -21,7 +21,8 @@
 ##? Examples:
 ##?   unbak core/main_bak.c
 
-set -euo pipefail
+# Set -uo pipefail for undefined variable check and pipeline failure propagation.
+set -uo pipefail
 
 # Check if docopts command is available.
 if ! command -v docopts > /dev/null 2>&1; then
@@ -36,6 +37,9 @@ version=$(grep "^#?" "$0" | cut -c 4-)
 # Get command-line arguments.
 args="$(docopts -h "$help" -V "$version" : "$@")"
 eval "$args"
+
+# Set -e to exit on non-zero command status.
+set -e
 
 # Define the backup file extension constant.
 readonly BAK_EXTENSION="_bak"
