Fix error with 'set -e' (must be set after docopts)

diff --git a/bin/uncolor b/bin/uncolor
--- a/bin/uncolor
+++ b/bin/uncolor
@@ -1,7 +1,7 @@
 #!/usr/bin/env bash
 
-#? uncolor, Time-stamp: <2023-12-31 Sun 13:10>
-#? Copyright (C) 2020-2023 Fabrice Niessen
+#? uncolor, Time-stamp: <2024-02-06 Tue 08:57>
+#? Copyright (C) 2020-2024 Fabrice Niessen
 #?
 #? License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
 #? This is free software: you are free to change and redistribute it.
@@ -18,7 +18,8 @@
 ##?   -h, --help                    display this help and exit
 ##?   -V, --version                 display version information and exit
 
-set -euo pipefail
+# Set -uo pipefail for undefined variable check and pipeline failure propagation.
+set -uo pipefail
 
 # Check if docopts command is available.
 if ! command -v docopts > /dev/null 2>&1; then
@@ -33,6 +34,9 @@ version=$(grep "^#?" "$0" | cut -c 4-)
 # Get command-line arguments.
 args="$(docopts -h "$help" -V "$version" : "$@")"
 eval "$args"
+
+# Set -e to exit on non-zero command status.
+set -e
 
 # Define the sed command as a string.
 sedCommand="sed -E 's/\x1b\[([0-9]{1,3}(;[0-9]{1,3})*)?[mK]//g'"
